/**
 * Schedule records (`api.md`'s "Schedules"), after apify-core's `ScheduleSchema`, `routes/schedules` and
 * `lib/schedules`. Running a schedule is `services/scheduler.ts`.
 */
import { generateId } from '../storage/ids.js';
import { KeyedMutex } from '../storage/mutex.js';
import type {
	ScheduleAction,
	ScheduledActorAction,
	ScheduledActorRunOptions,
	ScheduledTaskAction,
	ScheduleRecord,
	UserRecord,
} from '../storage/entities.js';
import { getRegistries } from '../storage/registries.js';
import { getOwnedActor, resolveOwnedActor } from './actors.js';
import { isJsonContentType } from './input-schema.js';
import { normalizeName, parseResourceReference } from './resource-reference.js';
import { assertValidCronExpression, computeNextRunAt, isSupportedTimezone } from './schedule-cron.js';
import { getOwnedTask, taskTitleFromName } from './tasks.js';

/** The platform's `DNS_SAFE_NAME_*` limits and its `ScheduleSchema` defaults. */
const NAME_MIN_LENGTH = 3;
const NAME_MAX_LENGTH = 63;
const DNS_SAFE_NAME_REGEX = /^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])$/;
const DEFAULT_NAME = 'my-schedule';
const TITLE_MAX_LENGTH = 40;
const DESCRIPTION_MAX_LENGTH = 5000;
const CRON_EXPRESSION_MAX_LENGTH = 100;
export const DEFAULT_CRON_EXPRESSION = '@daily';
export const DEFAULT_TIMEZONE = 'UTC';
/** The platform's `MAX_ACTORS_PER_SCHEDULER` / `MAX_TASKS_PER_SCHEDULER`. */
export const MAX_ACTIONS_PER_TYPE = 10;
/** The platform's `MAX_LOG_MESSAGES_PER_SCHEDULE`. */
export const MAX_LOG_MESSAGES = 250;

type JsonObject = Record<string, unknown>;

function isPlainObject(value: unknown): value is JsonObject {
	return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** A request the platform's schema would reject (`400` `schema-validation`). */
export class ScheduleValidationError extends Error {}

/** `400` `cron-expression-invalid`, the parser's message included. */
export class CronExpressionInvalidError extends Error {}

/** `409` `schedule-name-not-unique`. */
export class ScheduleNameTakenError extends Error {
	constructor(public readonly scheduleName: string) {
		super(`Some other schedule already has this name ("${scheduleName}").`);
	}
}

/** `403` `too-many-values`. */
export class TooManyActionsError extends Error {
	constructor(itemsName: string) {
		super(`Schedule can have at most ${MAX_ACTIONS_PER_TYPE} ${itemsName}.`);
	}
}

/** `404` `schedule-actor-not-found` / `schedule-actor-task-not-found`. */
export class ScheduleTargetNotFoundError extends Error {
	constructor(
		public readonly target: 'actor' | 'task',
		id: string,
	) {
		super(target === 'actor' ? `Actor with ID "${id}" not found` : `Actor task with ID "${id}" not found`);
	}
}

/** `400` `run-input-body-not-valid-json`. */
export class RunInputBodyNotJsonError extends Error {
	constructor() {
		super('The runInput.body is not valid JSON.');
	}
}

function fail(message: string): never {
	throw new ScheduleValidationError(message);
}

function optionalBoolean(body: JsonObject, field: string): boolean | undefined {
	const value = body[field];
	if (value === undefined || value === null) return undefined;
	if (typeof value !== 'boolean') fail(`${field} must be of type Boolean`);
	return value;
}

function optionalString(body: JsonObject, field: string, min: number, max: number): string | undefined {
	const value = body[field];
	if (value === undefined || value === null) return undefined;
	if (typeof value !== 'string') fail(`${field} must be of type String`);
	if (value.length < min) fail(`${field} must be at least ${min} characters`);
	if (value.length > max) fail(`${field} cannot exceed ${max} characters`);
	return value;
}

/** The writable fields of a schedule, as given in a create or update body; `actions` is validated apart. */
export type ScheduleFields = Pick<
	ScheduleRecord,
	'name' | 'title' | 'description' | 'cronExpression' | 'timezone' | 'isEnabled' | 'isExclusive' | 'notifications'
>;

/**
 * Checks `body` laid over `current` (or over the platform's defaults, when creating) the way the platform's
 * `ScheduleSchema` does, and returns the merged fields. A missing name or title is generated by `createSchedule`.
 */
export function mergeScheduleFields(
	body: JsonObject,
	current?: ScheduleRecord,
): Omit<ScheduleFields, 'name' | 'title'> & {
	name?: string;
	title?: string;
} {
	const name = optionalString(body, 'name', NAME_MIN_LENGTH, NAME_MAX_LENGTH) ?? current?.name;
	if (name !== undefined && !DNS_SAFE_NAME_REGEX.test(name)) fail('name failed regular expression validation');
	const title = optionalString(body, 'title', 0, TITLE_MAX_LENGTH) ?? current?.title;
	const description =
		body.description !== undefined
			? (optionalString(body, 'description', 0, DESCRIPTION_MAX_LENGTH) ?? undefined)
			: current?.description;

	const cronExpression =
		optionalString(body, 'cronExpression', 1, CRON_EXPRESSION_MAX_LENGTH) ??
		current?.cronExpression ??
		DEFAULT_CRON_EXPRESSION;
	if (!cronExpression.trim()) fail('cronExpression must be of type String');
	try {
		assertValidCronExpression(cronExpression);
	} catch (error) {
		throw new CronExpressionInvalidError(`Cron expression is not valid: ${(error as Error).message}`);
	}

	const timezone = optionalString(body, 'timezone', 1, 100) ?? current?.timezone ?? DEFAULT_TIMEZONE;
	if (!isSupportedTimezone(timezone)) fail('timezone is not an allowed value');

	let notifications = current?.notifications ?? { email: true };
	if (body.notifications !== undefined && body.notifications !== null) {
		if (!isPlainObject(body.notifications)) fail('notifications must be of type Object');
		const email = optionalBoolean(body.notifications, 'email');
		notifications = { email: email ?? notifications.email };
	}

	return {
		...(name !== undefined ? { name } : {}),
		...(title !== undefined ? { title } : {}),
		...(description !== undefined ? { description } : {}),
		cronExpression,
		timezone,
		isEnabled: optionalBoolean(body, 'isEnabled') ?? current?.isEnabled ?? false,
		isExclusive: optionalBoolean(body, 'isExclusive') ?? current?.isExclusive ?? true,
		notifications,
	};
}

const RUN_OPTION_TYPES: Record<keyof ScheduledActorRunOptions, 'string' | 'number' | 'boolean'> = {
	build: 'string',
	timeoutSecs: 'number',
	memoryMbytes: 'number',
	restartOnError: 'boolean',
};

function runOptionsFromAction(raw: unknown): ScheduledActorRunOptions | null | undefined {
	if (raw === undefined) return undefined;
	if (raw === null) return null;
	if (!isPlainObject(raw)) fail('runOptions must be of type Object');
	const options: Record<string, unknown> = {};
	for (const [key, type] of Object.entries(RUN_OPTION_TYPES)) {
		const value = raw[key];
		if (value === undefined || value === null) continue;
		if (typeof value !== type || (type === 'number' && !Number.isFinite(value))) {
			fail(
				`runOptions.${key} must be of type ${type === 'string' ? 'String' : type === 'number' ? 'Number' : 'Boolean'}`,
			);
		}
		if (type === 'number' && (value as number) < 0) fail(`runOptions.${key} must be at least 0`);
		options[key] = value;
	}
	return options as ScheduledActorRunOptions;
}

function runInputFromAction(raw: unknown): ScheduledActorAction['runInput'] {
	if (raw === undefined) return undefined;
	if (raw === null) return null;
	if (!isPlainObject(raw)) fail('runInput must be of type Object');
	const body = raw.body;
	if (typeof body !== 'string') fail('runInput.body must be of type String');
	const contentType = optionalString(raw, 'contentType', 1, 100) ?? 'application/json; charset=utf-8';
	if (isJsonContentType(contentType)) {
		try {
			JSON.parse(body);
		} catch {
			throw new RunInputBodyNotJsonError();
		}
	}
	return { body, contentType };
}

/** An action's `id` is kept when it names one of the schedule's current actions; otherwise it gets a new one. */
function actionId(raw: JsonObject, current: ScheduleRecord | undefined): string {
	const id = raw.id;
	if (id === undefined || id === null) return generateId();
	if (typeof id !== 'string') fail('id must be of type String');
	return current?.actions.some((action) => action.id === id) ? id : generateId();
}

/**
 * Checks the actions of a create or update body as the platform's `validateAndParseScheduleActions` does:
 * each names an existing Actor or task of `user`, with at most 10 of each kind. An Actor is accepted by
 * id or by name, like everywhere else here, and stored by id.
 */
export async function parseScheduleActions(
	user: UserRecord,
	raw: unknown,
	current?: ScheduleRecord,
): Promise<ScheduleAction[]> {
	if (!Array.isArray(raw)) fail('actions must be of type Array');
	const actors: ScheduledActorAction[] = [];
	const tasks: ScheduledTaskAction[] = [];
	for (const item of raw) {
		if (!isPlainObject(item)) fail('action must be of type Object');
		const id = actionId(item, current);
		if (item.type === 'RUN_ACTOR') {
			if (typeof item.actorId !== 'string' || !item.actorId) fail('actorId is required');
			const reference = parseResourceReference(item.actorId);
			const actor = reference.kind === 'empty-name' ? null : await resolveOwnedActor(user, reference);
			if (!actor) throw new ScheduleTargetNotFoundError('actor', item.actorId);
			const runInput = runInputFromAction(item.runInput);
			const runOptions = runOptionsFromAction(item.runOptions);
			actors.push({
				id,
				type: 'RUN_ACTOR',
				actorId: actor.id,
				...(runInput !== undefined ? { runInput } : {}),
				...(runOptions !== undefined ? { runOptions } : {}),
			});
		} else if (item.type === 'RUN_ACTOR_TASK') {
			if (typeof item.actorTaskId !== 'string' || !item.actorTaskId) fail('actorTaskId is required');
			if (!(await getOwnedTask(user.id, item.actorTaskId))) {
				throw new ScheduleTargetNotFoundError('task', item.actorTaskId);
			}
			if (item.input !== undefined && item.input !== null && !isPlainObject(item.input)) {
				fail('input must be of type Object');
			}
			tasks.push({
				id,
				type: 'RUN_ACTOR_TASK',
				actorTaskId: item.actorTaskId,
				...(isPlainObject(item.input) ? { input: item.input } : {}),
			});
		} else {
			fail('action.type must be one of: RUN_ACTOR, RUN_ACTOR_TASK');
		}
	}
	if (actors.length > MAX_ACTIONS_PER_TYPE) throw new TooManyActionsError('Actors');
	if (tasks.length > MAX_ACTIONS_PER_TYPE) throw new TooManyActionsError('Actor tasks');
	return [...actors, ...tasks];
}

/** The platform's `nextRunAt` after any write: recomputed from now, `null` while disabled. */
export function nextRunAtOf(
	schedule: Pick<ScheduleRecord, 'cronExpression' | 'timezone' | 'randomOffsetCoeff' | 'isEnabled' | 'lastRunAt'>,
	now = new Date(),
): string | null {
	if (!schedule.isEnabled) return null;
	try {
		return computeNextRunAt({
			cronExpression: schedule.cronExpression,
			randomOffsetCoeff: schedule.randomOffsetCoeff,
			currentDate: now,
			lastRunDate: schedule.lastRunAt ? new Date(schedule.lastRunAt) : null,
			timezone: schedule.timezone,
		}).toISOString();
	} catch (error) {
		throw new CronExpressionInvalidError(`Cron expression is not valid: ${(error as Error).message}`);
	}
}

/** Names are unique per user, so creating or renaming a schedule is serialised per user. */
const nameLocks = new KeyedMutex();

export async function listOwnedSchedules(userId: string): Promise<ScheduleRecord[]> {
	const all = await getRegistries().schedules.list();
	return all.filter((schedule) => schedule.userId === userId);
}

/** Cross-user listing, for the console and the scheduler only. */
export async function listAllSchedules(): Promise<ScheduleRecord[]> {
	return getRegistries().schedules.list();
}

export async function getScheduleById(id: string): Promise<ScheduleRecord | null> {
	return getRegistries().schedules.get(id);
}

export async function getOwnedSchedule(userId: string, id: string): Promise<ScheduleRecord | null> {
	const schedule = await getRegistries().schedules.get(id);
	return schedule && schedule.userId === userId ? schedule : null;
}

/** The platform's `generateUniqueName`: `my-schedule`, then `my-schedule-1`, `-2`, ... until it is free. */
function uniqueName(taken: ReadonlySet<string>): string {
	for (let suffix = 0; ; suffix++) {
		const name = suffix ? `${DEFAULT_NAME}-${suffix}` : DEFAULT_NAME;
		if (!taken.has(normalizeName(name))) return name;
	}
}

export type CreateScheduleInput = ReturnType<typeof mergeScheduleFields> & { actions: ScheduleAction[] };

/** Throws `ScheduleNameTakenError` for a name the user already has. */
export async function createSchedule(userId: string, input: CreateScheduleInput): Promise<ScheduleRecord> {
	return nameLocks.run(userId, async () => {
		const taken = new Set((await listOwnedSchedules(userId)).map((schedule) => normalizeName(schedule.name)));
		if (input.name !== undefined && taken.has(normalizeName(input.name)))
			throw new ScheduleNameTakenError(input.name);
		const name = input.name ?? uniqueName(taken);
		const now = new Date();
		const record: ScheduleRecord = {
			...input,
			id: generateId(),
			userId,
			name,
			title: input.title ?? taskTitleFromName(name).slice(0, TITLE_MAX_LENGTH),
			randomOffsetCoeff: Math.random(),
			createdAt: now.toISOString(),
			modifiedAt: now.toISOString(),
			nextRunAt: null,
			lastRunAt: null,
			log: [],
		};
		record.nextRunAt = nextRunAtOf(record, now);
		await getRegistries().schedules.set(record.id, record);
		return record;
	});
}

/** Throws `ScheduleNameTakenError` when the update renames the schedule to a name the user already has. */
export async function updateSchedule(
	schedule: ScheduleRecord,
	mutator: (current: ScheduleRecord) => ScheduleRecord,
): Promise<ScheduleRecord | null> {
	return nameLocks.run(schedule.userId, async () => {
		const others = (await listOwnedSchedules(schedule.userId)).filter((other) => other.id !== schedule.id);
		return getRegistries().schedules.update(schedule.id, (current) => {
			if (!current) return null;
			const next = mutator(current);
			if (others.some((other) => normalizeName(other.name) === normalizeName(next.name))) {
				throw new ScheduleNameTakenError(next.name);
			}
			const now = new Date();
			return { ...next, modifiedAt: now.toISOString(), nextRunAt: nextRunAtOf(next, now) };
		});
	});
}

export async function deleteSchedule(id: string): Promise<void> {
	await getRegistries().schedules.delete(id);
}

/** As on the platform, deleting an Actor or a task drops the schedule actions that would run it. */
export async function removeScheduleActionsFor(target: { actorId: string } | { actorTaskId: string }): Promise<void> {
	const matches = (action: ScheduleAction) =>
		'actorId' in target
			? action.type === 'RUN_ACTOR' && action.actorId === target.actorId
			: action.type === 'RUN_ACTOR_TASK' && action.actorTaskId === target.actorTaskId;
	for (const schedule of await listAllSchedules()) {
		if (!schedule.actions.some(matches)) continue;
		await getRegistries().schedules.update(schedule.id, (current) =>
			current ? { ...current, actions: current.actions.filter((action) => !matches(action)) } : null,
		);
	}
}

/** Whether `actorId` still exists for the schedule's owner; for the console's and scheduler's action labels. */
export async function scheduleActionTargetExists(schedule: ScheduleRecord, action: ScheduleAction): Promise<boolean> {
	return action.type === 'RUN_ACTOR'
		? (await getOwnedActor(schedule.userId, action.actorId)) !== null
		: (await getOwnedTask(schedule.userId, action.actorTaskId)) !== null;
}
